### 주문 생성
POST http://localhost:8080/orders/create
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}

### 주문 목록 조회
GET http://localhost:8080/orders
Accept: application/json

### 상품 단건 조회
GET http://localhost:8080/products/1
Accept: application/json

### 상품 목록 조회
GET http://localhost:8080/products
Accept: application/json